# -------------------------------------------------------------
# Configuration for the OKCVM Language Model Endpoints
# -------------------------------------------------------------
# You can directly provide an 'api_key' or use 'api_key_env'
# to load the key from an environment variable.
# -------------------------------------------------------------

chat:
  model: "kimi-k2-0905-preview"
  base_url: "https://api.moonshot.cn/v1"
  api_key: "sk-EAbA0oVT4w7Ia5iM7tpkGegf0kxqrvixrrZsWfW5tG54OdhR"

# Media generation models are optional.
# If you don't need a specific tool, you can comment it out or remove it.
media:
  image:
    model: "dall-e-3"
    api_key_env: "OPENAI_API_KEY"
    # No base_url needed if using default OpenAI

  speech:
    model: "tts-1"
    api_key_env: "OPENAI_API_KEY"

  # sound_effects:
  #   model: "some-sound-model"
  #   base_url: "..."
  #   api_key_env: "SOUND_API_KEY"

  # asr:
  #   model: "whisper-1"
  #   api_key_env: "OPENAI_API_KEY"
