# -------------------------------------------------------------
# Configuration for the OKCVM Language Model Endpoints
# -------------------------------------------------------------
# You can directly provide an 'api_key' or use 'api_key_env'
# to load the key from an environment variable.
# -------------------------------------------------------------

chat:
  model: "gpt-5"
  # base_url: "https://api.moonshot.cn/v1"  # For Moonshot AI (Kimi)
  base_url: "https://api.openai.com/v1"   # For OpenAI or compatible
  api_key_env: "OPENAI_API_KEY"           # Loads API key from the environment variable named OPENAI_API_KEY
  # api_key: "sk-..."                     # Or, paste your key directly here (less secure)

# Media generation models are optional.
# If you don't need a specific tool, you can comment it out or remove it.
media:
  image:
    model: "dall-e-3"
    api_key_env: "OPENAI_API_KEY"
    # No base_url needed if using default OpenAI

  speech:
    model: "tts-1"
    api_key_env: "OPENAI_API_KEY"

  # sound_effects:
  #   model: "some-sound-model"
  #   base_url: "..."
  #   api_key_env: "SOUND_API_KEY"

  # asr:
  #   model: "whisper-1"
  #   api_key_env: "OPENAI_API_KEY"
