# -------------------------------------------------------------
# Configuration for the OKCVM Language Model Endpoints
# -------------------------------------------------------------
# You can directly provide an 'api_key' or use 'api_key_env'
# to load the key from an environment variable.
# -------------------------------------------------------------

chat:
  model: "kimi-k2-0905-preview"
  base_url: "https://api.moonshot.cn/v1"
  # Reference an environment variable so secrets stay in .env
  api_key_env: "kimi_key"
  # Set to false if the upstream provider does not support SSE streaming.
  supports_streaming: true

# Media generation models are optional.
# If you don't need a specific tool, you can comment it out or remove it.
media:
  image:
    model: "dall-e-3"
    api_key_env: "OPENAI_API_KEY"
    # No base_url needed if using default OpenAI

  speech:
    model: "tts-1"
    api_key_env: "OPENAI_API_KEY"

  # sound_effects:
  #   model: "some-sound-model"
  #   base_url: "..."
  #   api_key_env: "SOUND_API_KEY"

  # asr:
  #   model: "whisper-1"
  #   api_key_env: "OPENAI_API_KEY"

workspace:
  # Path can be relative (resolved against this file) or absolute.
  path: "workspace"
  # Require a confirmation prompt before the server starts using the workspace.
  confirm_on_start: true
